### ISSUE TITLE
Ambiguity Around Picking and Gutting for Blue Belt

### ISSUE THREAD

**Issue by gmct** [crpearson/lockpicking#1]
For blue belt the requirements state you must pick and gut one of the locks from this list or similar. In the case of the lock from the list with a non-removable core this creates uncertainty as to whether you must gut another lock from the list or if any lock will do if you have not already demonstrated gutting skills. Clarification on the rules here could be helpful.

**Comment by crpearson** [comment]
You may gut another lock... Any lock will do. Changes made.
